version: '3'
services:
  api:
    build: .
    restart: always
    ports:
      - '4000:1323'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: dchackathon
  db:
    build: ./db
    restart: always
    ports:
      - '4001:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dchackathon
    volumes:
      - ./db/db-data:/var/lib/postgresql/data